name: "CI Slither"

on:
  schedule:
    - cron: "0 3 * * 0" # at 3:00am UTC every Sunday

jobs:
  lint:
    uses: "repo-path/reusable-workflows/.github/workflows/forge-lint.yml@main"

  slither-analyze:
    uses: "repo-path/reusable-workflows/.github/workflows/slither-analyze.yml@main"
